#pragma once

enum TagNumbers
{
	ImageWidth_n = 0x0100,
	ImageLength_n,
	BitsPerSample_n,
	ImageDescription_n = 0x010e,
	Make_n,
	Model_n,
	Orientation_n = 0x0112,
	XResolution_n = 0x011a,
	YResolution_n,
	ResolutionUnit_n = 0x0128,
	Software_n = 0x0131,
	DateTime_n,
	Artist_n = 0x013b,
	YCbCrCoefficients_n = 0x0213,
	ExifOffset_n = 0x8769,
	Indefined0_n = 0x010d,
	ExposureTime_n = 0x829a,
	FNumber_n = 0x829d,
	ExposureProgram_n = 0x8822,
	ISOSpeedRetings_n = 0x8827,
	ExifVersion_n = 0x9000,
	DateTimeOriginal_n = 0x9003,
	DateTimeDigitized_n,
	ComponentConfiguration_n = 0x9101,
	ShutterSpeedValue_n = 0x9201,
	ApertureValue_n,
	BrightnessValue_n,
	ExposureBiasValue_n,
	MaxApertureValue_n,
	MeteringMode_n = 0x9207,
	LightSource_n,
	Flash_n,
	FocalLength_n,
	MakerNote_n = 0x927c,
	SubSecTime_n = 0x9290,
	SubSecTimeOriginal_n,
	SubSecTimeDigitized_n,
	FlashPixVersion_n = 0xa000,
	ColorSpace_n,
	ExifImageWidth_n,
	ExifImageHeight_n,
	ExifInteroperabilityOffset_n = 0xa005,
	FocalPlaneXResolution_n = 0xa20e,
	FocalPlaneYResolution_n,
	FocalPlaneResolutionUnit_n,
	SensingMethod_n = 0xa217,
	FileSource_n = 0xa300,
	SceneType_n,
	Indefined1_n = 0xa401,
	Indefined2_n,
	WhiteBalance_n,
	DigitalZoomRatio_n,
	Indefined5_n,
	Indefined6_n,
	Indefined7_n,
	Contrast_n,
	Saturation_n,
	Sharpness_n,
	Indefined11_n,
	Indefined12_n,
	Indefined48_n = 0xa430,
	Indefined49_n,
	Indefined50_n,
	Indefined52_n = 0xa434
}TagNumber;